language: cpp

compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

before_script:
  - wget https://sourceforge.net/projects/boost/files/latest/download?source=directory --output-document=boost.tar.bz2
  - bzip2 -d boost.tar.bz2 && tar xf boost.tar && cd boost* && ./bootstrap.sh && sudo ./b2 install && cd ..
  - cmake CMakeLists.txt

script: make
