language: cpp

compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - cmake

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

before_script:
  - cmake CMakeLists.txt

matrix:
  fast_finish: true

    - env:    TEST_NAME="Boost 1.55"
      compiler: g++
      script: make
      packages:
       - libboost1.56-all-dev
    - env:    TEST_NAME="Boost 1.56"
      compiler: g++
      script: make
      packages:
       - libboost1.57-all-dev
    - env:    TEST_NAME="Boost 1.57"
      compiler: g++
      script: make
      packages:
       - libboost1.58-all-dev
     - env:    TEST_NAME="Boost 1.58"
      compiler: g++
      script: make
      packages:
       - libboost1.59-all-dev
     - env:    TEST_NAME="Boost 1.59"
      compiler: g++
      script: make
      packages:
       - libboost1.60-all-dev
     - env:    TEST_NAME="Boost 1.60"
      compiler: g++
      script: make
      packages:
       - libboost1.55-all-dev
 
