language: cpp

compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - cmake

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - wget http://ftp.debian.org/debian/pool/main/b/boost-defaults/libboost-all-dev_1.62.0.1_i386.deb
  - sudo dpkg -i libboost-all-dev_1.62.0.1_i386.deb

before_script:
  - cmake CMakeLists.txt

script: make
