dist: trusty
sudo: required
language: cpp

compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get update -qq
  - sudo apt-get install criterion-dev
  
addons:
  apt:
    packages:
    - libboost-all-dev
    - cmake
    - libgecode-dev

install:
  - wget https://cmake.org/files/v3.6/cmake-3.6.3.tar.gz
  - gunzip cmake-3.6.3.tar.gz
  - tar xf cmake-3.6.3.tar
  - cd cmake-3.6.3
  - ./bootstrap
  - make
  - sudo make install
  - cd ..

before_script:
  - cmake CMakeLists.txt

script:
  - make demo
  - make hypergraph
  - make test_model
  - make test_io

after_script:
  - test/test_model
  - test/test_algorithm
  - test/test_io
  - ./demo/demo --version
